### ISSUE TITLE
fork 删除请求

### ISSUE THREAD

**Issue by i0Ek3** [songlinlibit/songlinlibit.github.io#1]
你好，我是 [程序员在体制内的工作与生活是怎样的？](https://github.com/i0Ek3/work-and-life-in-system) 一文的作者。抱歉打扰到你，因为你之前 fork 的版本中存在一些敏感信息，可否请求你删除对应的 fork 分支？如果你愿意的话，可以重新 fork 现有的仓库，给你带来的不便，还请见谅。

**Comment by songlinlibit** [comment]
好的，了解！谢谢你的分享

i0Ek3 ***@***.***> 于2021年9月3日周五 下午12:47写道：

**Comment by i0Ek3** [comment]
好的，非常感谢。

**Comment by i0Ek3** [comment]
不好意思哈，我看[这个 fork](https://github.com/songlinlibit/work-and-life-in-system) 依然存在，可否请求再次删除？

**Comment by songlinlibit** [comment]
不好意思，之前忘记了，这段时间比较忙，给你带来困扰了，已经删除了

i0Ek3 ***@***.***> 于2021年9月27日周一 下午11:06写道：

**Comment by i0Ek3** [comment]
感谢理解，后面的版本可以随意 fork 了，很抱歉之前的情况。
